Repository seonWKim/ai-sidebar, pull requests merged in 2023-10, with the labels that each got.

#22 Add static page which users see when installed
  README.md
  main.gif
Labels: documentation, enhancement

#24 Update README.md
  README.md
Labels: documentation

#25 Fix the initial UI to remove the scrollbar
  src/views/SidePanel.vue
Labels: enhancement, good first issue

#27 Fix README
  README.md
Labels: documentation

#30 Add more detail in README.md
  README.md
  images/instruction.png
Labels: documentation, enhancement

#32 Add masking in the API key
  src/components/config/Settings.vue
Labels: enhancement

#33 Add api key setting guide
  src/assets/logo.png
  src/assets/logo.svg
  src/components/config/OpenaiApiKeyGuide.vue
  src/components/config/Settings.vue
  src/main.ts
  src/styles/main.css
Labels: enhancement

#34 docs
  README.md
Labels: documentation

#35 Add contributions section
  README.md
Labels: documentation, enhancement

#39 Update README.md
  README.md
Labels: enhancement

#42 Modify custom color settings into vuetify controlled colors
  src/components/Chat.vue
  src/components/config/OpenaiApiKeyGuide.vue
  src/components/config/OpenaiModelSelector.vue
  src/components/config/OpenaiRoleSelector.vue
  src/components/config/Settings.vue
  src/plugins/vuetify.ts
Labels: enhancement

#46 Add ways to mock openai response without using openai api key
  .env
  README.md
  src/service/openai.ts
  src/store/app.ts
Labels: enhancement

#51 Add comments related to stop button
  src/components/Chat.vue
Labels: enhancement

#52 Fix comment
  src/components/Chat.vue
  vite.config.ts
Labels: bug

#54 44 add a knob to control the temperature of openai response
  src/components/Chat.vue
  src/components/config/OpenaiTemperatureSlider.vue
  src/service/openai.ts
Labels: new feature

#57 Add textbox that we can use to add message template
  src/components/Chat.vue
Labels: new feature

#58 Add message template modal
  src/common/keys.ts
  src/components/Chat.vue
  src/components/ChatMessage.vue
  src/components/config/MessageTemplateModal.vue
  src/service/openai.ts
  src/store/app.ts
Labels: new feature

#61 56 add next textbox above and below current input textbox
  src/components/config/MessageTemplateModal.vue
Labels: bug

#62 Allow users to send previous N messages to OpenAI(context memoization)
  public/static/main.gif
  src/common/keys.ts
  src/common/message.ts
  src/components/Chat.vue
  src/components/config/MessageTemplateModal.vue
  src/components/config/OpenaiContextMemorizerModal.vue
  src/components/config/OpenaiModelSelector.vue
  src/components/config/OpenaiRoleSelector.vue
  src/components/config/OpenaiTemperatureModal.vue
  src/components/config/OpenaiTemperatureSlider.vue
  src/service/openai.ts
Labels: new feature, prompt engineering

#66 Fix button positions
  src/components/Chat.vue
Labels: enhancement

#67 Fix the initial UI to remove the scrollbar
  src/components/config/Settings.vue
  src/views/SidePanel.vue
Labels: bug

#69 Add theme selector
  src/common/keys.ts
  src/components/Chat.vue
  src/components/config/Settings.vue
  src/components/config/Themes.vue
  src/plugins/vuetify.ts
  src/views/SidePanel.vue
Labels: new feature

#70 Add clear button
  src/components/Chat.vue
Labels: new feature

#72 Enhance landing page when installed
  landing.html
  package-lock.json
  package.json
  public/js/service-worker.js
  src/Landing.vue
  src/assets/example-memorization.png
  src/assets/example-message-template.png
  src/assets/example-themes.png
  src/layouts/Default.vue
  src/layouts/ThemeLight.vue
  src/layouts/default/Default.vue
  src/layouts/default/DefaultView.vue
  src/main.ts
  src/router/index.ts
  src/store/app.ts
  src/views/About.vue
  vite.config.ts
Labels: enhancement

#76 Add show/hide message template feature
  src/common/keys.ts
  src/common/message.ts
  src/components/Chat.vue
  src/components/ChatMessage.vue
  src/components/config/MessageTemplateModal.vue
  src/components/config/OpenaiTemperatureModal.vue
  src/views/About.vue
Labels: enhancement, new feature

#77 21 add features to do prompt engineering with ease
  public/manifest.json
  src/common/keys.ts
  src/common/templates.ts
  src/components/Chat.vue
  src/components/config/MessageTemplateAddModal.vue
  src/components/config/MessageTemplateModal.vue
  src/store/app.ts
Labels: enhancement, new feature, prompt engineering

#79 Add custom shortcut for opening side panel
  public/js/service-worker.js
  public/manifest.json
  src/common/event.ts
  src/common/keys.ts
  src/components/config/Settings.vue
  src/main.ts
  src/store/app.ts
  src/views/About.vue
Labels: bug, new feature

#80 Add custom shortcut for opening side panel
  public/js/content-script.js
  src/components/config/Settings.vue
  src/main.ts
  src/views/About.vue
Labels: bug

#81 Enhance landing page by using aos
  src/main.ts
  src/views/About.vue
Labels: enhancement

#85 Fix About.vue
  src/views/About.vue
Labels: enhancement

#86 Fix aos config
  src/main.ts
Labels: enhancement

#90 88 add prettierrc and eslint support
  .all-contributorsrc
  .eslintrc.js
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/node.js.yml
  .prettierrc
  README.md
  index.html
  landing.html
  package-lock.json
  package.json
  public/html/page.html
  public/js/content-script.js
  public/js/script.js
  public/js/service-worker.js
  public/manifest.json
  public/static/image/site.webmanifest
  src/App.vue
  src/Landing.vue
  src/common/event.ts
  src/common/keys.ts
  src/common/message.ts
  src/common/templates.ts
  src/components/Chat.vue
  src/components/ChatMessage.vue
  src/components/Snackbar.vue
  src/components/config/MessageTemplateAddModal.vue
  src/components/config/MessageTemplateModal.vue
  src/components/config/OpenaiApiKeyGuide.vue
  src/components/config/OpenaiContextMemorizerModal.vue
  src/components/config/OpenaiModelSelector.vue
  src/components/config/OpenaiTemperatureModal.vue
  src/components/config/Settings.vue
  src/components/config/Themes.vue
  src/main.ts
  src/plugins/index.ts
  src/plugins/vuetify.ts
  src/router/index.ts
  src/service/openai.ts
  src/store/app.ts
  src/store/index.ts
  src/tests/service/openai.test.ts
  src/tsfix/vue3-markdown-it.d.ts
  src/views/About.vue
  src/views/SidePanel.vue
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#91 Fix the sidePanel to be opened as a global tab
  .github/workflows/node.js.yml
  package.json
  public/js/script.js
  public/js/service-worker.js
Labels: enhancement

#92 Fix `pushedKeyValues` to include only valid values
  public/js/content-script.js
Labels: bug

#95 Add image generation feature
  README.md
  main.png
  package.json
  src/App.vue
  src/common/chat-type.ts
  src/common/event.ts
  src/common/keys.ts
  src/common/message.ts
  src/common/mocks.ts
  src/components/chat/Chat.vue
  src/components/chat/config/ChatTypeSelector.vue
  src/components/chat/config/MessageTemplateAddModal.vue
  src/components/chat/config/MessageTemplateModal.vue
  src/components/chat/config/OpenaiApiKeyGuide.vue
  src/components/chat/config/OpenaiContextMemorizerModal.vue
  src/components/chat/config/OpenaiImageConfigurationModal.vue
  src/components/chat/config/OpenaiModelSelector.vue
  src/components/chat/config/OpenaiTemperatureModal.vue
  src/components/chat/config/Settings.vue
  src/components/chat/config/Themes.vue
  src/components/chat/message/ChatMessage.vue
  src/components/chat/message/ChatMessageImage.vue
  src/components/chat/message/ChatMessageText.vue
  src/components/etc/Snackbar.vue
  src/service/openai.ts
  src/views/About.vue
  src/views/SidePanel.vue
Labels: enhancement, new feature
